---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iioflux
  name: iioflux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iioflux
  template:
    metadata:
      labels:
        app: iioflux
    spec:
      containers:
      - name: iioflux
        image: jonkerj/iioflux:v1.0.0
        imagePullPolicy: Always
        env:
        - name: IIO_SENSORCONFIG
          value: /config/sensors.yaml
        - name: INFLUXDB_V2_BUCKET
          value: iioflux/autogen
        - name: INFLUXDB_V2_URL
          value: http://influxdb.influxdb:8086
        envFrom:
        - secretRef:
            name: influxdb-creds
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: config
---
apiVersion: v1
kind: Secret
metadata:
  name: influxdb-creds
type: Opaque
data:
  INFLUXDB_V2_TOKEN: Zm9vOmJhcg==
...
